version: '3.8'

services:
  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:80"  # Map port 4200 on your local machine to port 80 of the container
    restart: unless-stopped
    networks:
      - my_network
    volumes:
      - ./frontend:/app  # Optional: If you want live code synchronization during development

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Exposes port 80 of the container to port 80 on your machine
    depends_on:
      - angular-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Ensure you have a valid nginx configuration file
      - ./frontend/dist:/usr/share/nginx/html  # This ensures Nginx serves the built Angular app
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
