version: '3.8'

services:
  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-app
    networks:
      - my_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map custom Nginx config
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
