version: '3.8'

services:
  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-app
    networks:
      - my_network
    volumes:
      - ./frontend/dist:/app/dist  # After build, this will map the dist folder to the host

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map custom Nginx config
      - ./frontend/dist:/usr/share/nginx/html  # Serve the Angular app from Nginx
    depends_on:
      - angular-app  # Ensure Nginx starts after Angular build
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
