version: '3.8'

services:
  angular-app:
    build:
      context: ./frontend  # Path to your Angular project directory
      dockerfile: Dockerfile  # Dockerfile for building the Angular app
    container_name: angular-app
    networks:
      - my_network
    volumes:
      - ./frontend/dist:/app/dist  # Map the build output directory

  nginx:
    build:
      context: .  # Path to the directory containing Dockerfile.nginx
      dockerfile: Dockerfile.nginx  # Dockerfile for serving the Angular app
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map custom Nginx config
      - ./frontend/dist:/usr/share/nginx/html  # Serve the Angular app from Nginx
    depends_on:
      - angular-app  # Ensure Nginx starts after Angular build
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
